# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Achyutha Onti Srinivasan
title: Software Developer and Musician
email: achyuthontisrinivasan@gmail.com
website: www.1a111a05.github.io/aos

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  1A111A05
linkedin_username: achyuthontisrinivasan
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "channel/UCcLsQImRsG047zish6qcfOQ"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Reddit
  icon: fab fa-reddit-alien
  url: https://www.reddit.com/user/1A111A05/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/aos.png
about_content: | # this will include new lines to allow paragraphs
  Software Engineer with 5+ years of industry experience in the field of Endpoint Security and Data Backup. Experienced in application and system programming with proficiency in object oriented software system design. Currently working on payments backend and payment clients.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        sub_title:  April 2017 - February 2021
        description: |
          ![FireEye](https://github.com/1A111A05/AOS/raw/gh-pages/images/feye.png "fireeye")
      - layout: left
        caption: July 2019 - February 2021
        sub_title: Senior Software Development Engineer
        description: | # this will include new lines to allow paragraphs
          - Designed and implemented the Endpoint Malware Protection component for macOS which was built from scratch.
          - Worked on various critical field issues and also worked in consultation capacity for any new features being released.
      - layout: left
        sub_title: Software Development Engineer
        caption: July 2018 – July 2019
        description: | # this will include new lines to allow paragraphs
          - Worked on improving performance and detection efficacy in the product. This ensured the reduction in performance impact score by a factor of 3.3 times the earlier scores which when coupled with the improved detection rates lead us to be an AV-Comparatives approved Business security product with zero false positives.
          - Have contributed to features for supporting windows AMPPL certification requirements for FireEye Endpoint Security.
          - Worked on a Command line scanner by FireEye which is hosted in VirusTotal.
      - layout: left
        sub_title: Associate Software Development Engineer
        caption: Jan 2018 – July 2018
        description: | # this will include new lines to allow paragraphs 
          - Worked on the development of the FireEye Endpoint Agent for Malware Guard release. Malware Guard is a Machine Learning based Anti-Malware Engine which was added to the Endpoint Agent. This product went on to win the first place in NAVWAR Enterprise Awards for Artificial Intelligence Challenge
          - Built lateral movement detection engine POC as a hackathon project which was later productised and helped in detecting the Solarwinds breach of 2020
      - layout: left
        sub_title: Associate Software Development Engineer In Test
        caption: April 2017 – Jan 2018
        description: | # this will include new lines to allow paragraphs 
          - Designed and Implemented a performance test framework for the endpoint protection application to measure system impact due to AV. This was a dynamic framework which was capable of obtaining all related system metrics and caught multiple performance hits which were later fixed.
      
      - layout: right
        description: |
          ![Quest](https://github.com/1A111A05/AOS/raw/gh-pages/images/quest.png "quest")                   ![Dell](https://github.com/1A111A05/AOS/raw/gh-pages/images/dell.png "dell")
        sub_title: August 2016 - February 2017
      - layout: left
        # link_text: boringcompany.com
        caption: August 2016 - February 2017
        sub_title: Associate Software Development Engineer
        description: | # this will include new lines to allow paragraphs
          - Part Data Protection team of the Dell Software Group which was acquired by Francisco partners.
          - My role in this organisation was to develop applications in C for the DR series Purpose Based
          Backup Appliances (PBBA) that provided Deduplication and Compression for backing up data.
          - Some of the projects that I worked on were a slab allocator profiling module that was used to track fragmentation in the user space memory allocator in order to redesign the allocator to
          boost performance.
          - I also worked on a shared memory interface component that was used to track the samba VFS
          plugin requests to the deduplicating filesystem.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        caption: Vishveshwaraya Technological University, 2012 - 2016
        sub_title: Bachelor of Engineering (BE) Information Science
        description: | # this will include new lines to allow paragraphs
          PESIT-Bangalaore South Campus
          - Grade: 71.8%

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
